language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t testbuild -f Dockerfile.dev .

script:
  - docker run -e CI=true testbuild npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-eu-central-1-331658337748"
  bucket-path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: 'master'
